// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyM1bZvabUpqINlIyF66DEaiHSePhzrB0',
    appId: '1:175264872585:web:a1bda959708917c4f72e58',
    messagingSenderId: '175264872585',
    projectId: 'trasnporte-nataga---la-plata',
    authDomain: 'trasnporte-nataga---la-plata.firebaseapp.com',
    databaseURL: 'https://trasnporte-nataga---la-plata-default-rtdb.firebaseio.com',
    storageBucket: 'trasnporte-nataga---la-plata.firebasestorage.app',
    measurementId: 'G-6F10ND276Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpxgTKGvh3jJYylT6Qr6p2amgHmMzCTZQ',
    appId: '1:175264872585:android:57492986c90b764af72e58',
    messagingSenderId: '175264872585',
    projectId: 'trasnporte-nataga---la-plata',
    databaseURL: 'https://trasnporte-nataga---la-plata-default-rtdb.firebaseio.com',
    storageBucket: 'trasnporte-nataga---la-plata.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1azB18nvPpZeDpQkA8Gb_G9Ocjhcn9SE',
    appId: '1:175264872585:ios:6ee78a5c26ac61adf72e58',
    messagingSenderId: '175264872585',
    projectId: 'trasnporte-nataga---la-plata',
    databaseURL: 'https://trasnporte-nataga---la-plata-default-rtdb.firebaseio.com',
    storageBucket: 'trasnporte-nataga---la-plata.firebasestorage.app',
    androidClientId: '175264872585-beniod08nlf8tpv432v70qvaj6gtaboo.apps.googleusercontent.com',
    iosClientId: '175264872585-7apq8v0tjecg3qqleein6s2n4qfd84ic.apps.googleusercontent.com',
    iosBundleId: 'com.chopcode.agrogo',
  );
}
